# Generated by Django 3.2 on 2021-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0004_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('type1', '1'), ('type2', '2'), ('type3', '3'), ('type4', '4')], default='type1', help_text='Input type for item', max_length=5),
        ),
    ]
