# Generated by Django 3.2 on 2021-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0005_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='this is the best drink', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('favourite', 'favourite'), ('coffee', 'coffee'), ('fruit tea', 'fruit tea'), ('ICE BLENDED', 'ice blended'), ('snack', 'snack')], default='favourite', help_text='Input type for item', max_length=11),
        ),
    ]
