# Generated by Django 3.2 on 2021-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0008_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title here', max_length=100)),
                ('avatar', models.ImageField(upload_to='')),
                ('content', models.CharField(default='pls input here', max_length=300)),
            ],
        ),
    ]
