# Generated by Django 3.2 on 2021-12-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0011_alter_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
