# Generated by Django 3.2.9 on 2021-12-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0015_shippingaddress_instruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
