# Generated by Django 4.0 on 2021-12-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0016_rename_instruction_shippingaddress_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='')),
                ('content', models.CharField(default='Discount 90%', max_length=80)),
                ('expired', models.CharField(default='het han trong 2 ngay', max_length=18)),
            ],
        ),
    ]
