# Generated by Django 4.0 on 2021-12-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_app', '0017_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coffee_app.promotions'),
        ),
        migrations.AddField(
            model_name='promotions',
            name='discount',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='expired',
            field=models.CharField(default='het han trong 2 ngay', max_length=30),
        ),
    ]
